name: Java CI with Maven

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: write  # Разрешение на запись в репозиторий
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install

      - name: Install Allure
        run: |
          curl -o allure.zip -L https://github.com/allure-framework/allure2/releases/download/2.20.1/allure-2.20.1.zip
          sudo apt-get install -y unzip
          unzip allure.zip -d /opt/allure
          sudo ln -s /opt/allure/allure-2.20.1/bin/allure /usr/bin/allure

      - name: Run Tests
        run: mvn -Dmaven.test.failure.ignore=true test

      - name: Generate Allure Report
        run: |
          mkdir -p allure-report
          allure generate target/allure-results -o allure-report
        continue-on-error: true

      - name: List Allure Report Files
        run: ls -R allure-report

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
