# Workflow для публикации Allure отчета на GitHub Pages
name: Deploy Allure Report to Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install

      - name: Run Tests
        run: mvn -Dmaven.test.failure.ignore=true test

      - name: Install Allure
        run: |
          curl -o allure.zip -L https://github.com/allure-framework/allure2/releases/download/2.20.1/allure-2.20.1.zip
          sudo apt-get install -y unzip
          unzip allure.zip -d /opt/allure
          sudo ln -s /opt/allure/allure-2.20.1/bin/allure /usr/bin/allure

      - name: Generate Allure Report
        run: |
          mkdir -p allure-report
          allure generate target/allure-results --clean -o allure-report
        continue-on-error: true

      - name: Upload Allure Report as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './allure-report'  # Загрузка только папки allure-report

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

