# Workflow для публикации Allure отчета на GitHub Pages
name: Deploy Allure Report to Pages

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install

      - name: Install Allure
        run: |
          curl -o allure.zip -L https://github.com/allure-framework/allure2/releases/download/2.20.1/allure-2.20.1.zip
          sudo apt-get install -y unzip
          unzip allure.zip -d /opt/allure
          sudo ln -s /opt/allure/allure-2.20.1/bin/allure /usr/bin/allure


      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install ChromeDriver
        run: |
          CHROME_DRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)
          wget -N https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip -d /usr/bin/

      - name: Run Tests
        run: |
          mvn -Dmaven.test.failure.ignore=true \
              -Dselenide.browser=chrome \
              -Dselenide.headless=true \
              -Dchromeoptions.args="--no-sandbox --disable-dev-shm-usage --disable-gpu --remote-allow-origins=*" \
              test


      - name: Generate Allure Report
        run: |
          mkdir -p allure-report
          allure generate target/allure-results -o allure-report
        continue-on-error: true

      - name: List Allure Report Files Before Upload
        run: ls -R allure-report

      - name: Upload Allure Report as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './allure-report'  # Загрузка только папки allure-report

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

